#! /bin/sh

if [ -e dev/sda2 ]; then
  mount /dev/sda2 /mnt/software
fi

if [ -e dev/sdb1 ]; then
  mount /dev/sdb1 /mnt/data_tli/
fi

echo "Devices were mounted successfully:"
echo "    /dev/sda2 -> /mnt/software"
echo "    /dev/sdb1 -> /mnt/data_tli"
echo ""
