#!/bin/sh
# 將GAMMA的数据转为文本文件
prt_pt ../pt - ../pdef4 0 - 2 temp 1 -
awk {'print $3, 6150-$4, 1000*$5'} temp > data_pdef4

# 初始化
gmtset ANNOT_FONT_SIZE 9p ANNOT_OFFSET_PRIMARY 0.07i FRAME_WIDTH 0.04i MAP_SCALE_HEIGHT 0.04i \
LABEL_FONT_SIZE 10p LABEL_OFFSET 0.05i TICK_LENGTH 0.05i
output_file="pdef.ps"
# 创建调色板
makecpt -Crainbow -T-4/3/0.1 -I -V -Z > g.cpt
psbasemap -R0/5000/0/6150 -JX5.29i/3.92i -Ba1000f200::WeSn -P -K -V  > $output_file
psimage ../ave.ras -W5.29i/3.92i -O -V -K >> $output_file
psxy data_pdef4 -R -J -B -Cg.cpt -V -Sc0.03i -K -O >> $output_file

psscale -Cg.cpt -D5.3i/1.4i/1.9i/0.15i -E -I -O -B1::/:mm/\y: >> $output_file
ps2raster -A $output_file
