#!/bin/sh

# Data preparation
input_file=simlin.txt
output_file=pdef.ps

# 初始化
gmtset ANNOT_FONT_SIZE 9p ANNOT_OFFSET_PRIMARY 0.07i FRAME_WIDTH 0.04i MAP_SCALE_HEIGHT 0.04i \
LABEL_FONT_SIZE 10p LABEL_OFFSET 0.05i TICK_LENGTH 0.05i
# 创建调色板
makecpt -Crainbow -T-50/55/1 -I -V -Z > g.cpt
psbasemap -U"Simulated linear deformation v." -R0/3000/0/3000 -JX4i/4i -Ba1000f200::WeSn -P -K -V  > $output_file

psxy $input_file -R -J -B -Cg.cpt -V -Sc0.03i -K -O >> $output_file

psscale -Cg.cpt -D5.5i/1.4i/1.9i/0.15i -E -I -O -B20::/:mm/\y: >> $output_file
ps2raster -A $output_file
