#!/bin/sh

# Data preparation
input_file="vdh.txt"
output_file="pdef.ps"
awk '{print $2,6150-$3,$4}' $input_file >v.txt

# 初始化
gmtset ANNOT_FONT_SIZE 9p ANNOT_OFFSET_PRIMARY 0.07i FRAME_WIDTH 0.04i MAP_SCALE_HEIGHT 0.04i \
LABEL_FONT_SIZE 10p LABEL_OFFSET 0.05i TICK_LENGTH 0.05i
# 创建调色板
makecpt -Crainbow -T-20/33/1 -I -V -Z > g.cpt
psbasemap -U"Deformation Velocity near Xiqing" -R0/5000/0/6150 -JX5i/6.15i -Ba1000f200::WeSn -P -K -V  > $output_file
psimage ../ave.ras -W5i/6.15i -O -V -K >> $output_file #以ave.ras作为底图
psxy v.txt -R -J -B -Cg.cpt -V -Sc0.03i -K -O >> $output_file

psscale -Cg.cpt -D5.5i/1.4i/1.9i/0.15i -E -I -O -B5::/:mm/\y: >> $output_file
ps2raster -A $output_file
