#!/bin/sh
###########################################################
# Script that:
#       - Runs GAMMA DIFF-2-pass DInSAR with phase unwrapping and geocoding
#       - Processing for Ascending PALSAR interferometric pair data       
#       - Rui Zhang in ChengDu by 1/30/2010
# Usage:
#       -run the script
#       (./run_coreg master slave)
######################################
### parameter files
######################################
MASTER=$1
SLAVE=$2
M_P=${MASTER}
S_P=${SLAVE}
m_slc=../../slc_GAMMA/$M_P.slc
s_slc=../../slc_GAMMA/$S_P.slc
par_m=../../slc_GAMMA/$M_P.slc.par
par_s=../../slc_GAMMA/$S_P.slc.par
MS_off=$M_P-$S_P.off
width=$(awk '$1 == "range_samples:" {print $2}' $par_m)
######################################
###create the ISP processing/offset parameter file from MSP processing parameter and sensor files
######################################
#par_MSP ../$M_P/palsar.par ../$M_P/p$par_m $par_m
#par_MSP ../$S_P/palsar.par ../$S_P/p$par_s $par_s
######################################
###Supports interactive creation of offset/processing parameter file for generation of interferograms
###create_offset reads the SLC parameter files and queries the user for parameters(write into the .off file) required to calculate the offsets 
###using either the cross correlation of intensity or fringe visibility algorithms
### a. scence title: interferogram parameters
### b. range,azimuth offsets of SLC-2 relative to SLC-1(SLC samples):0 0
### c. enter number of offset measurements in range, azimuth: 32 32
### e. search window sizes(range, azimuth, nominal: 64 64)
### f. low correlation SNR threshold for intensity cross correlation 7.0
### g. offset in range to first interfergram sample 0
### h. width of SLCsection to processes (width of SLC-1)
######################################
echo -ne "$M_P-$S_P\n 0 0\n 32 32\n 64 64\n 7.0\n 0\n\n" > create_offset
######################################
create_offset $par_m $par_s $MS_off 1 1 1 <create_offset
rm -f create_offset

######################################
###first guess of the offsets can be obtained based on orbital information
###The position of the initial registration offset estimation can be indicated. As default the SLC-1 image center is used.
######################################
init_offset_orbit $par_m $par_s $MS_off
######################################
###improve the first guess, determines the initial offsets based on the cross-correlation function of the image intensities
###In order to avoid ambiguity problems and achieve an accutare estimates init_offset first be run with multi-looking
###followed by a second run at single look resolution
######################################
#init_offset $m_slc $s_slc $par_m $par_s $MS_off 6 16
init_offset $m_slc $s_slc $par_m $par_s $MS_off 3 3
init_offset $m_slc $s_slc $par_m $par_s $MS_off 1 1
######################################
###the first time offset_pwr and offset_fit, Estimation of offsets 
###first time with larger windowsize
###offset_pwr estimates the range and azimuth registration offset fields using correlation optimization of the detected SLC data
######################################
offset_pwr $m_slc $s_slc $par_m $par_s $MS_off $M_P-$S_P.offs $M_P-$S_P.off.snr 256 256 $M_P-$S_P.offsets 1 100 200 7.0 1

######################################
######determine the bilinear registration offset polynomial using a least squares error method
###offset_fit computes range and azimuth registration offset polynomials from offsets estimated by one of the programs offset_pwr
######################################
offset_fit $M_P-$S_P.offs $M_P-$S_P.off.snr $MS_off $M_P-$S_P.coffs $M_P-$S_P.coffsets 9.0 6 0
cp $M_P-$S_P.offsets offsets_pwr_1
cp $M_P-$S_P.coffsets coffsets_pwr_1
rm -f $M_P-$S_P.offs $M_P-$S_P.off.snr $M_P-$S_P.coffs $M_P-$S_P.coffsets $M_P-$S_P.offsets 

######################################
#######the 2nd-time offset_pwr and offset_fit(with smaller windowsize)
######################################
offset_pwr $m_slc $s_slc $par_m $par_s $MS_off $M_P-$S_P.offs $M_P-$S_P.off.snr 128 128 $M_P-$S_P.offsets 1 - - - 1
offset_fit $M_P-$S_P.offs $M_P-$S_P.off.snr $MS_off $M_P-$S_P.coffs $M_P-$S_P.coffsets 9.0 6 0
cp $M_P-$S_P.offsets offsets_pwr_2
cp $M_P-$S_P.coffsets coffsets_pwr_2
rm -f $M_P-$S_P.offs $M_P-$S_P.off.snr $M_P-$S_P.coffs $M_P-$S_P.coffsets $M_P-$S_P.offsets

######################################
###Estimates range and azimuth offset fields of a pair of SLC in support of image co-registration and offset tracking
######################################
offset_pwr_tracking $m_slc $s_slc $par_m $par_s $MS_off $M_P-$S_P.offs $M_P-$S_P.off.snr 32 32 $M_P-$S_P.offsets 2 9.0 40 40 - - - - 1
offset_fit $M_P-$S_P.offs $M_P-$S_P.off.snr $MS_off $M_P-$S_P.coffs $M_P-$S_P.coffsets 9.0 6 0
SLC_interp $s_slc $par_m $par_s $MS_off $S_P.rslc $S_P.rslc.par
SLC_intf $m_slc $S_P.rslc $par_m $S_P.rslc.par $MS_off $M_P-$S_P.int 1 1 - - 1 1
rasmph *.int $width - - - - - - - int.ras 0
######################################
###co-registration of the tow SLC images
###interf_SLC reads the single look complex SAR images SLC-1 and SLC-2, the corresponding SLC parameter files, the ISP offset parameter file
###interf_SLC use the range and azimuth offset polynomials(bi-linear in range and azimuth)to co-register SLC-2 to the geometry of SLC-1.
###Multi-look intensities of the co-registered images SLC-1 and SLC-2 are written to the files SLC-1.pwr and SLC-2.pwr.
######################################
#interf_SLC $m_slc $s_slc $par_m $par_s $MS_off $M_P-$S_P.pwr1 $M_P-$S_P.pwr2 $M_P-$S_P.int 3 15
######################################

